import { ArrowLeft, KeyRound, Landmark, Save, UserRound } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { BrandLogo } from '../components/BrandLogo'
import { getApiErrorMessage } from '../services/api-error'
import { closeAccount, getCurrentUser, updatePassword } from '../services/auth.service'
import { getCustomerRequests, requestSavingsAccount, updateCustomer } from '../services/customer.service'
import type { RequestResponse } from '../types/api'
import { formatPhone } from '../utils/format'

export function CustomerProfile() {
  const user=getCurrentUser()!; const [name,setName]=useState(user.name); const [email,setEmail]=useState(user.email); const [phone,setPhone]=useState(''); const [requests,setRequests]=useState<RequestResponse[]>([]); const [current,setCurrent]=useState(''); const [next,setNext]=useState(''); const [closePassword,setClosePassword]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState('')
  useEffect(()=>{void getCustomerRequests(user.id).then(setRequests).catch(()=>{})},[user.id])
  async function profile(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await updateCustomer(user.id,{name,email,phone:phone.replace(/\D/g,'')||undefined});setMessage('Dados atualizados.')}catch(x){setError(getApiErrorMessage(x,'Não foi possível atualizar.'))}}
  async function savings(){try{await requestSavingsAccount(user.id);setMessage('Solicitação enviada.');setRequests(await getCustomerRequests(user.id))}catch(x){setError(getApiErrorMessage(x,'Não foi possível solicitar.'))}}
  async function password(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await updatePassword(user.cpf,current,next);setCurrent('');setNext('');setMessage('Senha atualizada.')}catch(x){setError(getApiErrorMessage(x,'Não foi possível atualizar a senha.'))}}
  async function close(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await closeAccount(user.id,closePassword);setClosePassword('');setMessage('Solicitação de encerramento enviada.')}catch(x){setError(getApiErrorMessage(x,'Não foi possível encerrar.'))}}
  return <main className="min-h-screen bg-ink p-6"><div className="mx-auto max-w-5xl"><header className="flex justify-between"><BrandLogo compact/><Link to="/dashboard" className="text-zinc-400"><ArrowLeft size={16}/> Início</Link></header><h1 className="mt-10 text-3xl font-extrabold">Perfil</h1>{error&&<p className="mt-4 text-red-300">{error}</p>}{message&&<p className="mt-4 text-brand">{message}</p>}<div className="mt-6 grid gap-6 lg:grid-cols-2"><form onSubmit={profile} className="surface p-6"><UserRound className="text-brand"/><h2 className="mt-3 text-xl font-bold">Dados pessoais</h2><div className="mt-5 space-y-3"><input value={name} onChange={e=>setName(e.target.value)} className="input"/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="input"/><input value={phone} onChange={e=>setPhone(formatPhone(e.target.value))} placeholder="Telefone" className="input"/><button className="flex w-full justify-center gap-2 rounded-2xl bg-brand py-3 font-bold text-black"><Save size={16}/>Salvar</button></div></form><section className="surface p-6"><Landmark className="text-brand"/><h2 className="mt-3 text-xl font-bold">Solicitações</h2><button onClick={savings} className="mt-5 rounded-2xl border border-brand/30 px-4 py-3 text-sm font-bold text-brand">Solicitar conta poupança</button><div className="mt-4 divide-y divide-white/10">{requests.map(r=><div key={r.id} className="py-3 text-sm"><b>{r.requestType}</b><span className="ml-2 text-zinc-500">{r.status}</span></div>)}</div></section><form onSubmit={password} className="surface p-6"><KeyRound className="text-brand"/><h2 className="mt-3 text-xl font-bold">Alterar senha</h2><div className="mt-5 space-y-3"><input required type="password" value={current} onChange={e=>setCurrent(e.target.value)} placeholder="Senha atual" className="input"/><input required type="password" value={next} onChange={e=>setNext(e.target.value)} placeholder="Nova senha" className="input"/><button className="w-full rounded-2xl border border-white/10 py-3 font-bold">Atualizar senha</button></div></form><form onSubmit={close} className="surface border-red-500/20 p-6"><h2 className="text-xl font-bold text-red-300">Encerrar conta</h2><p className="mt-2 text-sm text-zinc-500">Confirme sua senha para enviar a solicitação.</p><input required type="password" value={closePassword} onChange={e=>setClosePassword(e.target.value)} placeholder="Senha de acesso" className="input mt-5"/><button className="mt-3 w-full rounded-2xl border border-red-400/30 py-3 font-bold text-red-300">Solicitar encerramento</button></form></div></div></main>
}
